# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
