# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
