# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180218_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
