# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180218_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='type',
        ),
    ]
