# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(default='tech', max_length=10),
            preserve_default=False,
        ),
    ]
