# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('TC', 'Technical'), ('HB', 'Hobbies'), ('ST', 'Startup'), ('SC', 'Student Council')], default='TC', max_length=2),
            preserve_default=False,
        ),
    ]
