# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_club_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('Technical', 1), ('Hobbies', 2), ('Startup', 3), ('Student Council', 4)], max_length=15),
        ),
    ]
