# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180218_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('TC', 'Technical'), ('HB', 'Hobbies'), ('ST', 'Startup'), ('SC', 'Student Council')], max_length=15),
        ),
    ]
