# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20180218_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='type',
            field=models.IntegerField(choices=[(1, 'Technical'), (2, 'Hobbies'), (3, 'Startup'), (4, 'Student Council')]),
        ),
    ]
