# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180218_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('TECH', 'Technical'), ('HOBBY', 'Hobbies'), ('START', 'Startup'), ('SC', 'Student Council')], max_length=5),
        ),
    ]
