# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=250)),
                ('startup_logo', models.CharField(max_length=1000)),
                ('startup_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.Startup'),
        ),
    ]
