# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='name',
            new_name='club_name',
        ),
    ]
