# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_description',
            field=models.CharField(default='description', max_length=2000),
            preserve_default=False,
        ),
    ]
