# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_club_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='event_name',
        ),
    ]
